name: parser
description: Visual Novel engine script language parser.
version: 1.0.2
homepage: https://github.com/lurkydismal/VN-script-parser

environment:
  sdk: '>=2.17.0-239.0.dev <3.0.0'

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.5
dependencies:
  args: ^2.4.2
