name: parser
description: Visual Novel engine ( https://github.com/lurkydismal/VN-engine-web ) script language parser.
version: 1.0.1
homepage: https://github.com/lurkydismal/VN-script-parser

environment:
  sdk: '>=2.17.0-239.0.dev <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {args: ^2.3.0}
